function(ConfigurePackaging)

    set(CPACK_PACKAGE_NAME "LlvmArmBaremetal")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "LLVM Project cross-compiled for ARM baremetal")
    set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
    set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
    set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
    set(CPACK_VERBATIM_VARIABLES YES)
    set(CPACK_GENERATOR TGZ)
    set(CPACK_SYSTEM_NAME armv7em)
    set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)

    # set(CPACK_RESOURCE_FILE_LICENSE

    include(CPack)

endfunction()
